<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Class1.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.105.1" />
    <PackageReference Include="FastReport.OpenSource" Version="2026.2.3" />
    <PackageReference Include="FastReport.OpenSource.Export.PdfSimple" Version="2026.2.3" />
    <PackageReference Include="FastReport.OpenSource.Web" Version="2026.2.3" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.3.11" />
    <PackageReference Include="Scalar.AspNetCore" Version="2.16.16" />
    <PackageReference Include="System.Security.Cryptography.Xml" Version="10.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Svod_Reports.BE.Service\Svod_Reports.BE.Service.csproj" />
  </ItemGroup>

</Project>
