<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Svod_Reports.BE.Service.Abstraction\Svod_Reports.BE.Service.Abstraction.csproj" />
  </ItemGroup>

</Project>
